name: Auto Solution Update

on:
  push:
    branches: [ main ]
    paths-ignore:
      - assets
      - .github
      - markdown
      - scripts
      - '.gitignore'
      - 'CodingTest.md'
      - 'LICENSE'
      - 'README.md'
      - 'algorithm_list.md'
      - 'change_level.log'
      - 'guideline_for_contribute.md'
      - 'picked.md'
      - 'status.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Run auto_update.py
      run: |
        python scripts/auto_update.py --push
    - name: Config Github
      run: |
        git config --local user.email "tony9402@naver.com"
        git config --local user.name "tony9402"
        git add .
        git commit -m "Auto Update (PUSH)"
        git push
